### ISSUE TITLE
XCode10 build error: multiple commands produce info.plist

### ISSUE THREAD

**Issue by shuoli84** [mattt/Godzippa#18]
error: Multiple commands produce 'xxx/iphoneos/Godzippa.framework/Info.plist'

**Comment by mattt** [comment]
Is this the same as #17? This should be fixed in the latest release. Can you please try again after updating to 2.1.0?

**Comment by shuoli84** [comment]
@mattt same one.

**Comment by georgbachmann** [comment]
Hey @mattt ... would be cool to push the new 2.1.0 to the official repo :)
Also... for me I still have the problem with 2.1.0 :( Any idea?
